apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM= # base64 encoded "password123"
  POSTGRES_USER: dXNlcg== # base64 encoded "user"
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  containers:
  - name: postgres
    image: postgres:latest
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_USER
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: postgres-config-volume
      mountPath: /etc/postgresql/postgresql.conf
      subPath: postgresql.conf
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-config-volume
    configMap:
      name: postgres-config
  - name: postgres-data
    emptyDir: {}
